databases:
  - name: karatachi_DB
    databaseName: karatachi_db_ynyv
    user: karatachi
    region: singapore

services:
  - type: web
    name: karatachi
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: karatachi_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

